### ISSUE TITLE
Not an Issue but...

### ISSUE THREAD

**Issue by sammygrey** [Sorrow446/WebM-Dynamic-Resolution#2]
How did you use FFmpeg to convert frames of different sizes to a WebM file that accounts for the different sizes? Every time I try, it resizes the images to fit within the scale of the first frame.

The command I have been running is ffmpeg -framerate 25 -f image2 -i folder/image_%03d.png -vf scale=-1:60 -pix_fmt yuva420p  output.webm if that helps at all.

**Comment by Sorrow446** [comment]
Here are the args for that.
```go
		args := []string{
			"-hide_banner", "-loglevel", "error", "-framerate", frameRate,
			"-f", "image2", "-i", base + "_r.png", "-c:v",
			"libvpx-vp9", "-pix_fmt", "yuva420p", base + ".webm",
		}
```

**Comment by sammygrey** [comment]
ty!
